{{- if and (not .Values.secrets.existingSecret) (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  GoogleOAuth__ClientId: {{ .Values.secrets.googleClientId | quote }}
  GoogleOAuth__ClientSecret: {{ .Values.secrets.googleClientSecret | quote }}
  Database__ConnectionString: {{ printf "Host=%s-postgresql;Port=%v;Database=%s;Username=%s;Password=%s" .Release.Name (.Values.global.postgresql.port | int) .Values.global.postgresql.database .Values.global.postgresql.username .Values.secrets.dbPassword | quote }}
{{- end }}
